#deberia comprobar ademas de la validez del token, 
#que el usuario todavia exista

GET /api/users HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImxvbWFkczEzMTMiLCJpYXQiOjE2OTUxNDYxMzksImV4cCI6MTY5NTIzMjUzOX0.3jqepuxooAiplXS8kiqe2UYOvl4i7rvs9rpOFb_qw8k

###

GET /api/users/62 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImxvbWFkczEzMTMiLCJpYXQiOjE2OTUxNDYxMzksImV4cCI6MTY5NTIzMjUzOX0.3jqepuxooAiplXS8kiqe2UYOvl4i7rvs9rpOFb_qw8k

###

GET /api/users/email/cesarhernanruscica@gmail.com HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTE2LCJpYXQiOjE2OTMwNTMzNzEsImV4cCI6MTY5MzEzOTc3MX0.ffT5kShp_dzzhYla0biRivpv-Trr1tGXm2C_VSVVJIM

###

POST /api/users/authenticate HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89

{
    "username": "bazooca"  ,
    "password": "password"
}

###

POST /api/users/register HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89

{
    "name" : "lomfas1", 
    "email" : "lomfasa1so@hotmail.com",
    "password" : "password",
    "roles_id" : 1,
    "photos_id" : 2,
    "real_name" : "Fulgencio rovira",  
    "birthday" : "1998-01-01", 
    "palettes_id" : 1
}

###################

PATCH /api/users/1 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImxvbWFkczEzMTMiLCJpYXQiOjE2OTUxNDYxMzksImV4cCI6MTY5NTIzMjUzOX0.3jqepuxooAiplXS8kiqe2UYOvl4i7rvs9rpOFb_qw8k

{
    "name" : "nuevo_charly", 
    "email" : "nuevo.luisito@hotmail.com",
    "password" : 1234,
    "roles_id" : 1,
    "photos_id" : 2,
    "real_name" : "Luis Beltran",  
    "birthday" : "1901-03-05", 
    "palettes_id" : 1
}

####

DELETE /api/users/144 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InBlcHVkbyIsImlhdCI6MTY5MTg0NzQyOCwiZXhwIjoxNjkxOTMzODI4fQ.Cqgs_CjflwayMj6gIZJ_wJr-D5jyFkeExLZoQT0CMbg

####

GET /api/users/register HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89

### Prueba con el host cyclic
GET /api/users HTTP/1.1
Host: https://wild-gray-crow-toga.cyclic.cloud
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImJhem9vY2EiLCJpYXQiOjE2OTQ5Njc3OTIsImV4cCI6MTY5NTA1NDE5Mn0.02VDQQtGsb7JjDRzrt_rX4KBoiqnvwtENsSjymZCYX0