#deberia comprobar ademas de la validez del token, 
#que el usuario todavia exista

GET /api/users HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im5pY28iLCJpYXQiOjE2OTUxMzkzMzEsImV4cCI6MTY5NTIyNTczMX0.R_qtiUCiDTqgddc2aJlcXAtYfAPPZ77gq9qoD8E7euA

###

GET /api/users/3 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im5pY28iLCJpYXQiOjE2OTUxMzkzMzEsImV4cCI6MTY5NTIyNTczMX0.R_qtiUCiDTqgddc2aJlcXAtYfAPPZ77gq9qoD8E7euA

###

GET /api/users/name/nico HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im5pY28iLCJpYXQiOjE2OTUxMzkzMzEsImV4cCI6MTY5NTIyNTczMX0.R_qtiUCiDTqgddc2aJlcXAtYfAPPZ77gq9qoD8E7euA

###

POST /api/users/authenticate HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89

{
    "username": "bazooca"  ,
    "password": "password"
}

###

POST /api/users/register HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89

{
    "name" : "lomads1313", 
    "email" : "lomadsa13s31o@hotmail.com",
    "password" : "password",
    "roles_id" : 1,
    "photos_id" : 2,
    "real_name" : "Fulgencio rovira",  
    "birthday" : "1998-01-01", 
    "palettes_id" : 1
}

###################

PATCH /api/users/62 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImJhem9vY2EiLCJpYXQiOjE2OTE2NzIyNTYsImV4cCI6MTY5MTc1ODY1Nn0.hevhiumNKsv9Vegjj8Bxhcv441yZ4nDnDhXK_pGvxJg

{
    "name" : "nuevo_luis", 
    "email" : "nuevo.luisito@hotmail.com",
    "password" : 1234,
    "roles_id" : 1,
    "photos_id" : 2,
    "real_name" : "Luis Beltran",  
    "birthday" : "1901-03-05", 
    "palettes_id" : 1
}

####

DELETE /api/users/3 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im5pY28iLCJpYXQiOjE2OTUxMzkzMzEsImV4cCI6MTY5NTIyNTczMX0.R_qtiUCiDTqgddc2aJlcXAtYfAPPZ77gq9qoD8E7euA

####

GET /api/users/register HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89

### Prueba con el host cyclic
GET /api/users HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im5pY28iLCJpYXQiOjE2OTMyNjYwNDgsImV4cCI6MTY5MzM1MjQ0OH0.BM0Uxgf7mVM9DnEqt_GZJ5qVRbtkhIH7Hbszn9XofI8